# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '08bd1f726b464fd36d8398301ca86ec2'
  config.secret_key = '481bddc824f4e86baebd0000b36ca661'
  config.default_from = 'support@tree-of-us.com'
  config.api_version = 'v3.1'
end
